		.ORIG X3000													

		AND R0, R0, #0 ;BASE
		AND R1, R1, #0 ;STORE FIRST NUM, LATER STORE SIGN OF SUM
		AND R2, R2, #0 ;STORE SECOND NUM, Later store sum, 
		AND R3, R3, #0 ;compare sum result
		AND R4, R4, #0 ;sign of first num
		AND R5, R5, #0 ;sign of second num

		LEA R0, BASE ; load x3100 address into R0
		LDW R0,R0,#0;
 
		AND R4, R4, #0  ; clear R4
		LDB R1, R0, #0  ; load byte r1 with byte in address r0(x3100) this will cause condition codes to be set
		BRN FIRSTNEG	;IF FIRST NUM IS NEGATIVE
		BRP FIRSTPOS	;IF FIRST NUM IS POSITIVE
CHECK1		NOP		;R4 HAS SIGN OF 1ST NUM

		AND R5, R5, #0
		LDB R2, R0, #1
		BRN SECNEG	;IF FIRST NUM IS NEGATIVE
		BRP SECPOS	;IF FIRST NUM IS POSITIVE
CHECK2		NOP		;R5 HAS SIGN OF 2ND NUM

		ADD R2, R2, R1	;ADD THE TWO NO.S
		STB R2, R0, #2	;STORE IN X3102

		AND R1, R1, #0		
		LDB R2, R0, #2	;READ BACK FROM x3102 TO GET ACTUAL SIGN IN 8 BITS
		BRN SUMNEG	;IF SUM IS NEGATIVE
		BRZP SUMPOS	;IF SUM IS POSITIVE OR ZERO --> SET FLAG AS POSITIVE
SUMCHECK	NOP		;R1 HAS SIGN OF SUM
		
		ADD R2, R4, R4	;CHECKING IF FIRST NUM IS ZERO
		BRZ ZEROFOUND	;
		ADD R4, R5, R5	;CHECKING IF SECOND NUM IS ZERO
		BRZ ZEROFOUND	;

		AND R3, R3, #0 ;

		ADD R3, R5, R4	;COMPARE SIGNS OF 1ST AND 2ND NUMBER
		BRNP MATCHSIGN	;IF THEY HAVE SAME SIGN --> CHANCE OF OVERFLOW --> GOTO FUNCTION TO CHECK SUM SIGN
		
;ONLY REACHES HERE IF SIGNS ARE DIFFERENT OR ZERO FOUND--> NO CHANCE OF OVERFLOW
ZEROFOUND	AND R2, R2, #0
		STB R2, R0, #3	;STORE 0 IN X3103
		BR DONE		;SKIP EVERYTHING ELSE		

MATCHSIGN	AND R3, R3, #0 ;
		ADD R3, R1, R4	;COMPARE SIGNS OF SUM AND ANY NUM(FIRST(R4) OR SECOND(R5))
		BRZ OVERFLOW	;SUM HAS DIFFERENT SIGN -->OVERFLOW CONFIRMED

;ONLY REACHES HERE IF SUM HAS SAME SIGN AS BOTH NUMBERS --> NO OVERFLOW CONFIRMED
		AND R2, R2, #0
		STB R2, R0, #3	;STORE 0 IN X3103
		BR DONE		;SKIP EVERYTHING ELSE

OVERFLOW	AND R2, R2, #0
		ADD R2, R2, #1
		STB R2, R0, #3	;STORE 1 IN X3103
		BR DONE		;SKIP EVERYTHING ELSE

SUMNEG		AND R1, R1, #0
		ADD R1, R1, #-1
		BR SUMCHECK

SUMPOS		AND R1, R1, #0
		ADD R1, R1, #1
		BRnzp SUMCHECK


FIRSTNEG	AND R4, R4, #0
		ADD R4, R4, #-1
		BR CHECK1

FIRSTPOS	AND R4, R4, #0
		ADD R4, R4, #1
		BR CHECK1

SECNEG		AND R5, R5, #0
		ADD R5, R5, #-1
		BR CHECK2

SECPOS		AND R5, R5, #0
		ADD R5, R5, #1
		BR CHECK2

DONE		HALT 	

BASE		.FILL X-f
		.END